# Generated by Django 5.2.13 on 2026-04-07 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisetemplate',
            name='demo_url',
            field=models.TextField(blank=True, default='', help_text='Comma-separated image URLs (for slideshow) or a YouTube embed URL'),
        ),
    ]
